preload= ~/Wallpaper.png
#wallpaper=DP-1, ~/Wallpaper.png
#wallpaper=HDMI-A-1, ~/Wallpaper.png

wallpaper {
    monitor = DP-1
    path = ~/Wallpaper.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/Wallpaper.png
    fit_mode = cover
}


